### PR TITLE
Fix misnamed property in leaching package

### PR DESCRIPTION
**Pull request by andrewlee94**
## Summary/Motivation:
Whilst working on other code, I noticed that `dens_mass` was named `dens_mol` in the leaching properties. This PR fixes this.

## Changes proposed in this PR:
- Fix misnamed property.
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Review by agarciadiego — APPROVED** [review]
LGTM

**Review by ArkoprabhoDasgupta — APPROVED** [review]

**Review by bpaul4 — APPROVED** [review]

**Review by MarcusHolly — CHANGES_REQUESTED** [review]
It seems like this naming error may have been copied over into other files as well, so it might be worth addressing here: https://github.com/prommis/prommis/blob/main/src/prommis/solvent_extraction/ree_aq_distribution.py

**Comment by andrewlee94** [comment]
@MarcusHolly @ArkoprabhoDasgupta How do we want to go about fixing the misnamed property in the SX properties? Are there other PRs we should get merged first to avoid conflicts?

**Comment by ArkoprabhoDasgupta** [comment]
> @MarcusHolly @ArkoprabhoDasgupta How do we want to go about fixing the misnamed property in the SX properties? Are there other PRs we should get merged first to avoid conflicts?

I think it would be fine, because the only thing that is changing is the definition of the density term of the constant term of the solvent that is water, I do not see any change in the way the state variables names, so I think it would be fine

**Review by MarcusHolly — APPROVED** [review]

**Comment by andrewlee94** [comment]
@MarcusHolly @ArkoprabhoDasgupta I've renamed the properties in the SX model as well. I will note however that there were no tests for the density in the SX models, so we need to work on improving test coverage.

**Pull request merged**
