### PR TITLE
Update requirements for idaes-pse and watertap for IDAES 2.7.0

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Reviewer's checklist / merge requirements:
- [x] The head branch (i.e. the "source" of the changes) is not the `main` branch on the PR author's fork
- ~[ ] Documentation~
- ~[ ] Tests~
- ~[ ] Diagnostic tests for models~

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
This seems to be the only test that's currently failing:
image

**Comment by bpaul4** [comment]
> This seems to be the only test that's currently failing: image

@lbianchi-lbl the test failure is actually expected based on the PrOMMiS costing, our code is working as expected. In a recent update, WaterTAP edited the Nanofiltration Zero Order model and the operating costs were changed from variable costs to fixed costs: https://github.com/watertap-org/watertap/commit/b3841990182272b56113b1a1f67eaafab3113581#diff-3fa2d70dc03953aa214d43201339a7960e1c6a814e9d892eef30d5de29fd58ec. The test for the individual fixed operating cost variables still pass as those values did not change, but there is a new fixed cost that is picked up so the value of the total fixed cost is larger now.

The fix here is to update the operating cost variable object and value checks. I can do this and push to this PR.

**Comment by lbianchi-lbl** [comment]
After incorporating the newest set of changes from watertap-org/watertap#1541 in preparation for the WaterTAP 1.2.0rc0 release, there's a new test failure seemingly due to a numerical discrepancy:

image

@bpaul4 do you have any insights on what might be causing this?

**Comment by bpaul4** [comment]
The dye desal parameters for the Nanofiltration Zero Order model were updated in https://github.com/watertap-org/watertap/pull/1528, which modifies the membrane properties and affect of performance on required area. As a result, the estimated capital cost and fixed operating cost change as well. Updating the values is safe and reflects the current nanofiltration properties and cost calculations.

**Review by MarcusHolly — APPROVED** [review]
LGTM

**Review by bpaul4 — APPROVED** [review]

**Pull request merged**
