### PR TITLE
surrogate_model_precipitator

### PR DESCRIPTION
**Pull request by agarciadiego**
## Addresses Issue: 
Adding a surrogate model for the precipitator

## Summary/Motivation:
Changing split fraction to a surrogate model based on pH

## Changes proposed in this PR:

- [x] add surrogate models based on pH
- [ ] add surrogate models based on acid dosage
- [ ] rework path so you don't have repeated files
- [ ] workflow on how to run the surrogates in sequence with the flowsheet (if necessary)

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@agarciadiego is still possible for the March release?

**Comment by lbianchi-lbl** [comment]
@agarciadiego I'm assuming this won't make it for the March release as that would need the PR to be merged within the week - let me know if that's not the case.

**Comment by agarciadiego** [comment]
> @agarciadiego I'm assuming this won't make it for the March release as that would need the PR to be merged within the week - let me know if that's not the case.

I'm hoping to get this done and merged during the week. Can we wait to move it out of the release to Monday?

**Comment by ksbeattie** [comment]
@agarciadiego, moving this now to the Dec release.  What's the news on this?  It seems stalled.

**Comment by agarciadiego** [comment]
Closed with PR #99

**Comment by agarciadiego** [comment]
See PR #99

**Pull request closed without merging**
