### PR TITLE
Revised oxalate roaster model to include Ca species in the unit model

### PR DESCRIPTION
**Pull request by jinliangma**
## Changes proposed in this PR:
- Added Ca related components
- Note that the precipitate property package should be revised to include Ca in the species list to test this revised unit model

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by MarcusHolly** [comment]
@jinliangma The UKy flowsheet tests seem to be passing for now, but while we're on this topic, have you added the liquid/moisture inlet for the roaster into this repo? Last I checked, you had it on a local branch, but I'm not sure if it ever made it into a PR.

**Comment by jinliangma** [comment]
Regarding the moisture inlet, I need to add to it to this PR later or in a new PR.

**Comment by lbianchi-lbl** [comment]
@jinliangma @agarciadiego I'm taking this off the March release board - let me know if you instead plan on getting this merged within this week.

**Comment by agarciadiego** [comment]
> @jinliangma @agarciadiego I'm taking this off the March release board - let me know if you instead plan on getting this merged within this week.

If we can get the reviews this could be merged by march

**Review by bpaul4 — APPROVED** [review]
LGTM

**Review by MarcusHolly — CHANGES_REQUESTED** [review]
Andrew has mentioned earlier that we want to avoid using values from Aspen for licensing reasons. So I'm not sure if we should merge this PR just yet. Also there are some conflicts with the UKy flowsheet tests as a result of a PR that just got merged.

**Pull request closed without merging**
